### ISSUE TITLE
Suggestion: PWA

### ISSUE THREAD

**Issue by ilDon** [jufabeck2202/go-wasm-pdfmerge#7]
Hello, fisrt great project, I work a lot with PDFs and I wouldn't mind to have a local first, fast PDF editing tool. 
In that perspective, I think this is one of those projects that could benefit a lot  from being a PWA, is that on the roadmap?

**Comment by julianfbeck** [comment]
Yea sounds like a great addition!

**Comment by Akxe** [comment]
This can now be closed :)
